services:
  kafka:
    image: confluentinc/cp-kafka:7.9.8@sha256:b38b43301027c5a8990f778e478d2b7384d3fd62cc1aeff6768b89fbd898172a
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_NUM_PARTITIONS=3
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    ports: ["9092:9092"]
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.8@sha256:48ca7843cdf2e9d35f96b86efd290e81fcedd595cd5d7df8fde3a6724c3c5869
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
