name: Run docker compose

inputs:
  compose_file:
    description: Boolean value that specifies whether docker compose up should be run.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run docker compose
      if: inputs.compose_file != 'false'
      uses: hoverkraft-tech/compose-action@3846bcd61da338e9eaaf83e7ed0234a12b099b72 # v2.4.1
      with:
        compose-file: ${{ inputs.compose_file }}
