name: Run docker compose

inputs:
  compose_file:
    description: Boolean value that specifies whether docker compose up should be run.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run docker compose
      if: inputs.compose_file != 'false'
      uses: hoverkraft-tech/compose-action@05da55b2bb8a5a759d1c4732095044bd9018c050 # v2.4.3
      with:
        compose-file: ${{ inputs.compose_file }}
